### PR TITLE
Fix unuseable event

### PR DESCRIPTION
**Pull request by Schrank**
Add transport object to make it possible to change the merge variable value

Unfortuantely references doesn't work in this scenario, so we need a transport object.

### CODE REVIEW

**Comment by Santiagoebizmarts** [comment]
Hello @Schrank 

Thanks for your contribution.
This works okay in several test cases, can you elaborate on which case this does not work?

Kind Regards

**Comment by Schrank** [comment]
@Santiagoebizmarts Perfect! I can't reproduce it easily... tested it today a few hours. Do you have a sample observer I can use? Then we can remove this PR :-)

**Comment by Santiagoebizmarts** [comment]
@Schrank We realized that in the [explanation](https://ebizmarts.com/forums/topics/view/24875) it was not specified that the event needs to be declared in the global node.

If you follow all the steps explained there you should have no problem with creating your custom Merge field.

**Comment by sprankhub** [comment]
The important part is that you set the new value on the event object and NOT on the observer.

Works:

    $observer->getEvent()->setMergeFieldValue('your_val');

Does not work:

    $observer->setMergeFieldValue('your_val');

**Pull request closed without merging**
