### PR TITLE
Add support for profile updates

### PR DESCRIPTION
**Pull request by ihor-sviziev**
**Steps to reproduce:**
1. Configure Mailchimp module & webhook
2. Subscribe subscriber via Magento
3. Go to Mailchimp, find subscriber that was added in step 2
4. Update First name & click "save" button (on mailchimp)

**Actual result:**
On Magento we have old first name

**Expected result**
On Magento we have updated first name

Note: _profile method had issue when subscriber is not related to customer even after adding "profile" case to processWebhookData method

### CODE REVIEW

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for your contribution, I made a little change because to load the customer by id Magento requires to set a website.

Regards.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts That change that you did brakes loading customer in case when customer account scope was set to "per website".
http://docs.magento.com/m1/ce/user_guide/customers/account-scope.html

In this case you can't find customer only by id. You need also provide website id.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts  I added new commit that fixes issue that I described above

**Comment by Santiagoebizmarts** [comment]
Hello @ihor-sviziev 

The website you are setting may not be the website where the customer created the account. It will return always the default website. I am implementing some changes in the webhook process because I realized it has some flaws including this one.

Thank you very much!

**Comment by Santiagoebizmarts** [comment]
If name and lastname are empty in MailChimp it removes the names in Magento

**Comment by Santiagoebizmarts** [comment]
This has been fixed in the latest version.
Thanks for your contribution @ihor-sviziev

**Pull request closed without merging**
