### PR TITLE
Fix block type

### PR DESCRIPTION
**Pull request by fooman**
Prevent Mage_Core_Exception: Invalid block type: Ebizmarts_MailChimp_Block_Group_Types

### CODE REVIEW

**Comment by Santiagoebizmarts** [comment]
Hello @fooman 

Thanks for your feedback. When exactly are you getting that exception?

Kind Regards.

**Comment by fooman** [comment]
I noticed it in the log after hitting the checkout success page.

**Comment by Santiagoebizmarts** [comment]
Thanks for your contribution @fooman @dbashyal 

Kind Regards.

**Comment by Santiagoebizmarts** [comment]
This is the first half of the issue #912

**Comment by seansan** [comment]
Great! I presume this was backported to 1.1.15 as an urgent fix?

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

This has been solved already. See issue https://github.com/mailchimp/mc-magento/issues/912
Please note even though the exception is thrown everything works as expected.

Kind Regards.

**Pull request merged**
