### PR TITLE
closes issue 657

### PR DESCRIPTION
**Pull request by jan-lukowiak**
enable checkout subscription even if isEcomSyncDataEnabled is not enabled for this storeview

### CODE REVIEW

**Comment by Santiagoebizmarts** [comment]
Hello @jan-lukowiak 

Thank you very much for your contribution.
Actually the checkout subscription should be allowed only if Subscription is enabled.
The change you made is okay but would be better adding another if doing the check $helper->isSubscriptionEnabled($storeId) containing the block with the if(isset($post)) inside.

Please add that and I will accept the PR.

Regards.

**Comment by jan-lukowiak** [comment]
Thanks @Santiagoebizmarts 

Sure I've added the condition.

**Comment by Santiagoebizmarts** [comment]
Hi @jan-lukowiak 

Please add the expects for the new function in the test and we will be good to go.
Thanks again for your help into making the extension better.

Kind Regards.

**Comment by Santiagoebizmarts** [comment]
Thank you @jan-lukowiak 

We really appreciate your contribution!

Kind Regards.

**Pull request merged**
